FROM ubuntu:22.04 AS llvm-builder
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        curl \
        ca-certificates \
        build-essential \
        cmake \
        python3 \
        lld \
        ninja-build \
        pkg-config \
        libssl-dev \
        srecord \
        binutils-m68k-linux-gnu \
        vim \
        nano \
        bsdmainutils \
        file \
    && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 --branch release/16.x https://github.com/llvm/llvm-project.git /llvm-project

# Lowering the number of jobs may help you solve out of memory crashes
# Increasing the number of jobs will save you time :)
ARG NUM_JOBS=6
WORKDIR /llvm-m68k
RUN cmake /llvm-m68k \
    -S /llvm-project/llvm \
    -G Ninja \
    "-DLLVM_USE_LINKER=lld" \
    "-DCMAKE_BUILD_TYPE=Release" \
    "-DLLVM_ENABLE_ASSERTIONS=ON" \
    "-DLLVM_PARALLEL_LINK_JOBS=1" \
    "-DLLVM_TARGETS_TO_BUILD=AArch64;AMDGPU;ARM;AVR;BPF;Hexagon;Lanai;Mips;MSP430;NVPTX;PowerPC;RISCV;Sparc;SystemZ;VE;WebAssembly;X86;XCore" \
    "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=M68k" \
    "-DLLVM_ENABLE_PROJECTS=clang;lld" \
    && cmake --build . --parallel ${NUM_JOBS} --target install \
    && rm -rf /llvm-project
